### ISSUE TITLE
Update readme w/ installation instructions, etc

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart2js_info#68]
`pub global activate..` etc etc

**Comment by sigmundch** [comment]
We currently have this in front of the documentation for every tool, for example: https://github.com/dart-lang/dart2js_info#code-deps-tool

Do you mean something else or just to have a quick summary upfront?

**Comment by kevmoo** [comment]
Oh...sorry. didn't see that.

I'd roll all of that to the top of the readme. 😄
