### ISSUE TITLE
The binary program does not contain 'main'

### ISSUE THREAD

**Issue by jaracil** [dart-lang/dart2js_info#75]
Hi. I'm getting errors when installing dart2js_info.

`dart --version`

Dart VM version: 2.2.0 (Unknown timestamp) on "linux_x64"

`pub global activate dart2js_info`

...
Precompiling executables... (1.5s)
Failed to precompile dart2js_info:inject_text:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:usage_exception:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:deferred_library_size:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:code_deps:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:debug_info:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:function_size_analysis:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:live_code_size_analysis:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:text_print:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:diff:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:to_json:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:deferred_library_layout:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:show_inferred_types:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:to_binary:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:convert:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:to_proto:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:library_size_split:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:deferred_library_check:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Failed to precompile dart2js_info:coverage_log_server:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
Precompiled dart2js_info:tools.

**Comment by sigmundch** [comment]
Thanks for reporting the issue!

Apparently `pub global activate` builds all libraries in `bin/` as executable scripts because they could technically be invoked via `pub global run dart2js_info:name`. 

I checked locally and I believe the issue should be gone now (starting with version 0.6.1)
