### ISSUE TITLE
Restrict specific files in "Deferred library verification"

### ISSUE THREAD

**Issue by Aetet** [dart-lang/dart2js_info#77]
Hello.
Thank you for awesome tool for dart2js profiling.
I want to restrict what files should be present at main chunk. 
Example.

I have 2 libs: `Main` and `Folder`.
Folder consist two files:
```
folder_view.dart
folder_service.dart
```

`folder_service` reused at `Folder` and `Main`. So it would be at main chunk. 
`folder_view` should be at separated chunk `Folder`.

I want to have a restriction. `folder_view` should be present at `Folder` chunk only. 
But `folder_service` should be at `Folder` & `Main`. 

How can I restrict this with "Deferred library verification"?

**Comment by sigmundch** [comment]
Thanks for your question!

At this time, the `deferred_check` tool has one restriction: the yaml manifest only lets you distinguish between packages, but not between libraries between packages. 

If `main.dart` was in `package:a`, `folder_view.dart` was in `package:b`, `folder_service.dart` was in `package:c`, and your deferred import for `folder_service` used the prefix `service`, then you could write the following yaml manifest:

```yaml
main:
  include:
   - a
   - b

service:
  include:
   - c
```

This would tell the tool that `package:b` (containing `folder_view`) is OK in the main output unit, but `package:c` (containing `folder_service`) is on the `service` output unit.

If the main thing you want to check is that `folder_service` is not part of main, then it might be enough to use:
```yaml
main:
  include:
    - a
    - b
  exclude:
    - c
```

If your code is not split in packages like that, the current yaml specification from this tool might be too hard to work with. In that case, you may want to consider forking from it so you can write a custom tool of your own that does what you need. 

Another option for you might be to use the `deferred_layout` tool and post process the output to check for what you are looking for.

Hope this helps!

**Comment by Aetet** [comment]
Thanks for response!
